#!/usr/bin/env python
import sys

from dunyadesktop_app import toplevel
toplevel.install()

import mainui_makam

app = mainui_makam.QApplication(sys.argv)
mainwindow_makam = mainui_makam.MainWindowMakam()
mainwindow_makam.show()
app.exec_()
